1006_db2/practice/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

1006_db2/ws1/데일리+실습_db_03_1_P/practice1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('todos/', include('todos.urls')),
    path('admin/', admin.site.urls),
]

1006_db2/ws1/데일리+실습_db_03_1_P/todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/cancel/', views.cancel, name='cancel'),
    path('<int:pk>/completed/', views.completed, name='completed'),

]

1006_db2/accounts/models.py
from django.db import models

# Create your models here.

1006_db2/articles/models.py
from django.db import models

# Create your models here.

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

1006_db2/ws1/데일리+실습_db_03_1_P/todos/models.py
from email.policy import default
from unittest.util import _MAX_LENGTH
from django.db import models
from django.conf import settings

# 조건 2
class Todo(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    completed = models.BooleanField(default=False)

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields

1006_db2/ws1/데일리+실습_db_03_1_P/todos/forms.py
from .models import Todo
from django import forms

class TodoForm(forms.ModelForm):

    class Meta:
        model = Todo
        # fields = '__all__'
        exclude = ('author', )

1006_db2/accounts/views.py
from django.shortcuts import render

# Create your views here.

1006_db2/articles/views.py
from django.shortcuts import render

# Create your views here.

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            user = form.get_user()
            auth_login(request, user)
            return redirect('todos:index')
    else:
        form = AuthenticationForm()

    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)



def logout(request):
    auth_logout(request)
    return redirect('todos:index')

1006_db2/ws1/데일리+실습_db_03_1_P/todos/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from django.contrib.auth.decorators import login_required
# from django.http import HttpResponse, HttpResponseForbidden
from .models import Todo
from .forms import TodoForm

# Create your views here.
def index(request):
    todos = Todo.objects.all()
    context = {
        'todos' : todos,
    }
    return render(request, 'todos/index.html', context)

def create(request):
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save(commit=False)
            todo.author = request.user
            todo.save()
        return redirect('todos:index')
    else:
        form = TodoForm()
    context = {
        'form':form,
    }
    return render(request, 'todos/create.html', context)

def delete(request, pk):
    todo = Todo.objects.get(pk=pk)
    if request.user.is_authenticated:
        todo = Todo.objects.get(pk=pk)
        if request.user == todo.author:
            todo.delete()
            return redirect('todos:index')
    return redirect('todos:index', todo.pk)

def cancel(request, pk):
    todo = Todo.objects.get(pk=pk)
    if request.user.is_authenticated:
        todo = Todo.objects.get(pk=pk)
        if request.user == todo.author:
            todo.completed = 0
            todo.save()
            return redirect('todos:index')
    return redirect('todos:index', todo.pk)

def completed(request, pk):
    todo = Todo.objects.get(pk=pk)
    if request.user.is_authenticated:
        todo = Todo.objects.get(pk=pk)
        if request.user == todo.author:
            todo.completed = 1
            todo.save()
            return redirect('todos:index')
    return redirect('todos:index', todo.pk)

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
  <h2>Login</h2>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>login</button>
  </form>
  <a href="{% url 'accounts:signup' %}">Signup</a>
{% endblock %}

1006_db2/ws1/데일리+실습_db_03_1_P/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
  <h2>Sign Up</h2>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button>SignUp!</button>
  </form>
{% endblock %}

1006_db2/ws1/데일리+실습_db_03_1_P/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Todos</title>
</head>
<body>
  <div class="container">
   {% if request.user.is_authenticated %}
     <a href="{% url 'todos:create' %}">NEW</a>
     <a href="{% url 'accounts:logout' %}">logout</a>
   {% else %}
     <a href="{% url 'accounts:login' %}">login</a>
     <a href="{% url 'accounts:signup' %}">signup</a>
   {% endif %}
  {% block content %}
  
  {% endblock content %}
  </div>
</body>
</html>

1006_db2/ws1/데일리+실습_db_03_1_P/todos/templates/todos/create.html
{% extends 'base.html' %}

{% block content %}
  <h1>CREATE</h1>
  <form action="{% url 'todos:create' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>

{% endblock content %}

1006_db2/ws1/데일리+실습_db_03_1_P/todos/templates/todos/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>Todo</h1>
  <hr>
  {% for todo in todos %}
    <li>{{ todo.author }} - {{ todo.title }}</li>
    {% if request.user == todo.author %}
      <form action="{% url 'todos:delete' todo.pk %}" metho="POST">
        {% csrf_token %}
        <input type="submit" value="삭제하기">
      </form>

      {% if todo.completed == 1 %}
      <form action="{% url 'todos:cancel' todo.pk %}" metho="POST">
        {% csrf_token %}
        <input type="submit" value="취소하기">
      </form>
      {% endif %}

      {% if todo.completed == 0 %}
        <form action="{% url 'todos:completed' todo.pk %}" metho="POST">
          {% csrf_token %}
          <input type="submit" value="완료하기">
        </form>
      {% endif %}
    {% endif %}
  {% empty %}
    <li>작성된 글이 없습니다.</li>
  
  {% endfor %}
  
  
{% endblock content %}